#[derive(Clone)]
pub struct IslandWidgets {
    pub notch_capsule: gtk4::Box,
    pub default_view: gtk4::Box,
    pub music_view: gtk4::Box,
    pub track_label: gtk4::Label,
    pub art_container: gtk4::Box,
    pub visualizer_box: gtk4::Box,
    pub notification_badge: gtk4::Box,
    pub badge_title: gtk4::Label,
    pub badge_desc: gtk4::Label,
    pub badge_icon_container: gtk4::Box,
    pub popover_title: gtk4::Label,
    pub popover_artist: gtk4::Label,
    pub popover_art_container: gtk4::Box,
    pub popover_app_name: gtk4::Label,
    pub play_btn_icon: gtk4::Image,
    pub notification_view: gtk4::Box,
    pub notif_art_container: gtk4::Box,
    pub notif_title_lbl: gtk4::Label,
    pub notif_body_lbl: gtk4::Label,
}
